<a href="https://colab.research.google.com/github/samanvisingh/whatsapp_chat_analyzer-/blob/main/SectionA_%3Csamanvi_singh%3E.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# question 1
# ==(equality) sees if the value are equal
# is (identity) checks uf the memory location are same
list_a = [10,20,40]
list_b = [10,20,40]
print(list_a == list_b)
print(list_a is list_b)

True
False


In [ ]:
# question 2
# immutability - means that data cannot be changed after execution by others
# mutable - list , dict , set
# immutable - int , float , bool , str , tuple , frozenset

In [ ]:
# question 3
#  the predict output would be false because 0.1+ 0.2 = 0.30000000 and == checks for eqaulity and no it is not equal as computers read it in binary so false
a = float('0.1')
b =float ('0.2')
c = float ('0.3')
print(a+b == c)

False


In [ ]:
# question 4
# tuple cannot be changed. it is usedd for fixed data and tuple has reserved memory it never grow and you cannot use dictionary keys with pist python will crash

In [ ]:
# question 5
# list in is like searching for specific book on a bookshelf
# without hash you have to check every single item one by one until you find what you need
# in dict run your key through hash that calculates exact memory

In [ ]:
# question 6
# range() only takes integers and will crash if you try a step like 0.5. numpy.arange() handles decimals perfectly
# range() is lazy and just generates numbers on the fly, so it barely uses any memory. arange() instantly creates a full array of all the numbers in memory
# Because arange() gives you a NumPy array, you can do bulk math on it (like np.arange(5) * 10). If you try to multiply a standard range() like that, Python throws an erro

In [ ]:
# question 7
#if a = [1,2,3] and x = [4,5]

#append: just throws the whole x list at the end.
result = [1, 2, 3, [4, 5]]

#extend: unpacks the numbers and merges them.
result = [1, 2, 3, 4, 5]

#insert: same as append but u pick the exact spot (like index 1).
result = [1, [4, 5], 2, 3]

In [ ]:
# question 8
nums =[10,20,30,40]
a,*b,c =nums
print("a =",a)
print("b=",b)
print("c=",c)

a = 10
b= [20, 30]
c= 40


In [ ]:
# question 9
#/ (normal division)
#just standard division, gives you the exact decimal answer.
(-7) / 2 = -3.5

#// (floor division)
#divides and rounds DOWN to the nearest whole number. (careful with negatives here: -3.5 rounds down to -4, not -3).
(-7) // 2 = -4

#% (modulo / remainder)
#gives you the remainder of the division. python does weird math with negative remainders, but it uses the -4 from the floor division. 2 * -4 = -8, so it needs a remainder of 1 to get back to -7.
(-7) % 2 = 1

#** (exponent / power)
#just means to the power of. so it's -7 squared.
(-7) ** 2 = 49

In [ ]:
# question 10
# / normal division - just standard division , gives the exact decimal
x = -7
y = 2
print(x/y)
# // floor division divides and round off the output (down) to nearest integer
print(x//y)
# % modulus gives you remainder
print(x%y)
# ** exponent means to the power off
print(x**y)

-3.5
-4
1
49


In [ ]:
# question 10
# numpy packs all the data in tightly in one continnuos group , while pyhton data scatter the data all over
# python list waste time in checking whether the data is string , float or int before doing maths while numpy save times by forcing everything to be same type and skiping the checking thing entirely


In [ ]:
# SECTION B

In [ ]:
# Q.11
#a) predicted output before running:
# matrix 1 will just update the very first number.
#matrix 2 will update the first number in every single row.

#actual output after running:
[[99, 0, 0], [0, 0, 0], [0, 0, 0]]
[[99, 0, 0], [99, 0, 0], [99, 0, 0]]
matrix1 = [[0] * 3 for _ in range(3)]
matrix2 = [[0] * 3] * 3
matrix1[0][0] = 99
matrix2[0][0] = 99
print(matrix1)
print(matrix2)

# why:
#the for loop in matrix1 creates 3 completely separate lists in memory. matrix2 uses * 3, which just creates 3 pointers to the exact same list, so editing one row accidentally changes all of the

[[99, 0, 0], [0, 0, 0], [0, 0, 0]]
[[99, 0, 0], [99, 0, 0], [99, 0, 0]]


In [ ]:
# x will get the 4 but y will remain same .
# both a and b will get that 4
x = [1, 2, 3]
y = x
x = x + [4]
print("x =", x)
print("y =", y)
a = [1, 2, 3]
b = a
a += [4]
print("a =", a)
print("b =", b)
# why it is giving this output :
# doing x = x + [4] creates a brand new list for x leaving the y behind doing += edit the list directly

x = [1, 2, 3, 4]
y = [1, 2, 3]
a = [1, 2, 3, 4]
b = [1, 2, 3, 4]


In [ ]:
# the output  for 1st is 10 and 20 , for 2nd its 30 , for 3rd 10 , 10 , 10 for 4th it is 3, 3,3
# the fifth one will crash as text and int cannot be added and also for last it again give error as we can not add str and int
print("10" + "20")
print(10 + 20)
print("10" * 3)
print(10 * "3")
print("10" + 20)
print(int("10") + 20)

In [ ]:
# output before running 5,5,hello,0,10,default,[0]
print(0 or 5)
print(5 or 0)
print(None or "hello")
print(0 and 5)
print(5 and 10)
print([] or "default")
print([0] or "default")
# short-circuit evaluation means python is lazy and stops checking left-to-right the exact second it finds a definitive answer (first true for or, first false for and)

5
5
hello
0
10
default
[0]


Section -C


In [ ]:
# question 16
# method a
x = 10
y = 5

x = x + y
y = x - y
x = x - y

# method b
x = 10
y = 5

x = x ^ y
y = x ^ y
x = x ^ y

# method c
x = 10
y = 5

x, y = y, x
# method c is most pythonic as it just uses one line of code and super easy to read


In [ ]:
# question 17
price = float(input("enter item price: "))
qty = int(input("enter quantity: "))

subtotal = price * qty
gst = subtotal * 0.18

if subtotal < 500:
    delivery = 40.0
else:
    delivery = 0.0

final_total = subtotal + gst + delivery

print(f"Subtotal: ₹{subtotal:.2f}")
print(f"GST (18%): ₹{gst:.2f}")
print(f"Delivery: ₹{delivery:.2f}")
print("-" * 24)
print(f"Total: ₹{final_total:.2f}")

enter item price: 345
enter quantity: 6
Subtotal: ₹2070.00
GST (18%): ₹372.60
Delivery: ₹0.00
------------------------
Total: ₹2442.60


In [ ]:
# question 18
temp = float(input("enter temperature value: "))
unit = input("enter unit (C or F): ")

unit = unit.upper()

if unit == "C":
    result = (temp * 9/5) + 32
    print(f"result: {result:.2f} F")
elif unit == "F":
    result = (temp - 32) * 5/9
    print(f"result: {result:.2f} C")
else:
    print("error: invalid unit. please enter C or F.")

enter temperature value: 77.77
enter unit (C or F): F
result: 25.43 C


In [ ]:
# question 19
num = int(input("enter a 4 digit number "))

d4 =num % 10
num = num // 10

d3 =num % 10
num = num // 10

d2 = num % 10
num = num // 10

d1 = num % 10

total = d1 + d2 + d3 + d4
print("sum of digits :" , total )

enter a 4 digit number 7701
sum of digits : 15


In [ ]:
# question 20
data = input ("enter something :")
result =  int (data)
print("type: int, value :", result)


enter something :26
type: int, value : 26


C2


In [ ]:
# question 21
income = float(input("enter income:"))
slab1 = 0.0  # 3L to 7L (5%)
slab2 = 0.0  # 7L to 10L (10%)
slab3 = 0.0  # 10L to 12L (15%)
slab4 = 0.0  # 12L to 15L (20%)
slab5 = 0.0  # Above 15L (30%)

if income > 1500000:
    slab5 = (income - 1500000) * 0.30
    slab4 = 300000 * 0.20
    slab3 = 200000 * 0.15
    slab2 = 300000 * 0.10

    slab1 = 400000 * 0.05
elif income > 1200000:
    slab4 = (income - 1200000) * 0.20
    slab3 = 200000 * 0.15
    slab2 = 300000 * 0.10
    slab1 = 400000 * 0.05
elif income > 1000000:
    slab3 = (income - 1000000) * 0.15
    slab2 = 300000 * 0.10
    slab1 = 400000 * 0.05
elif income > 700000:
    slab2 = (income - 700000)*0.10
    slab1 = 400000 *0.05
elif income > 300000:
    slab1 = (income - 300000) * 0.05
total_tax = slab1 + slab2 + slab3 + slab4 + slab5
print("--- Tax Breakdown ---")
print("Up to ₹3L (0%): ₹0.00")
print(f"₹3L - ₹7L (5%): ₹{slab1:.2f}")
print(f"₹7L - ₹10L (10%): ₹{slab2:.2f}")
print(f"₹10L - ₹12L (15%): ₹{slab3:.2f}")
print(f"₹12L - ₹15L (20%): ₹{slab4:.2f}")
print(f"Above ₹15L (30%): ₹{slab5:.2f}")
print("-" * 25)
print(f"Total Tax: ₹{total_tax:.2f}")

enter income:10000.25
--- Tax Breakdown ---
Up to ₹3L (0%): ₹0.00
₹3L - ₹7L (5%): ₹0.00
₹7L - ₹10L (10%): ₹0.00
₹10L - ₹12L (15%): ₹0.00
₹12L - ₹15L (20%): ₹0.00
Above ₹15L (30%): ₹0.00
-------------------------
Total Tax: ₹0.00


In [ ]:
# question 22
pan = input("enter PAN: ")

count = 0
for char in pan:
    count = count + 1

if count != 10:
    print("Invalid PAN — length must be exactly 10 characters")
elif not pan[0:5].isalpha() or not pan[0:5].isupper():
    print("Invalid PAN — first 5 characters must be uppercase letters")
elif not pan[5:9].isdigit():
    print("Invalid PAN — characters 6 to 9 must be digits")
elif not pan[9].isalpha() or not pan[9].isupper():
    print("Invalid PAN — last character must be an uppercase letter")
else:
    print("Valid PAN")

enter PAN: ABCDE1234F
Valid PAN


In [ ]:
# question 23
units = float(input("enter units consumed: "))

slab1 = 0.0
slab2 = 0.0
slab3 = 0.0
slab4 = 0.0

if units > 200:
    slab4 = (units - 200) * 8.15
    slab3 = 100 * 7.10
    slab2 = 50 * 5.55
    slab1 = 50 * 4.10
elif units > 100:
    slab3 = (units - 100) * 7.10
    slab2 = 50 * 5.55
    slab1 = 50 * 4.10
elif units > 50:
    slab2 = (units - 50) * 5.55
    slab1 = 50 * 4.10
else:
    slab1 = units * 4.10

energy_charge = slab1 + slab2 + slab3 + slab4
fixed_charge = 110.0
tax = (energy_charge + fixed_charge) * 0.06

total_bill = energy_charge + fixed_charge + tax

print("--- BESCOM Electricity Bill ---")
print(f"0-50 units (@4.10): ₹{slab1:.2f}")
print(f"51-100 units (@5.55): ₹{slab2:.2f}")
print(f"101-200 units (@7.10): ₹{slab3:.2f}")
print(f"Above 200 units (@8.15): ₹{slab4:.2f}")
print(f"Fixed Charge: ₹{fixed_charge:.2f}")
print(f"Govt Tax (6%): ₹{tax:.2f}")
print("-" * 29)
print(f"Total Bill: ₹{total_bill:.2f}")

enter units consumed: 412
--- BESCOM Electricity Bill ---
0-50 units (@4.10): ₹205.00
51-100 units (@5.55): ₹277.50
101-200 units (@7.10): ₹710.00
Above 200 units (@8.15): ₹1727.80
Fixed Charge: ₹110.00
Govt Tax (6%): ₹181.82
-----------------------------
Total Bill: ₹3212.12


In [ ]:
# question 24
runs = int(input("enter runs scored: "))
balls = int(input("enter balls faced: "))

if balls == 0:
    print("error: balls faced cannot be zero. player hasn't batted yet.")
else:
    sr = (runs / balls) * 100
    print(f"Strike Rate: {sr:.2f}")

    if sr > 150:
        print("Class: Explosive (T20 finisher)")
    elif sr > 100:
        print("Class: Aggressive (Top order T20)")
    elif sr >= 75:
        print("Class: Steady (ODI anchor)")
    else:
        print("Class: Defensive (Test match)")

enter runs scored: 206
enter balls faced: 50
Strike Rate: 412.00
Class: Explosive (T20 finisher)


In [ ]:
# question 25
weight = float(input("enter weight in kg: "))
height_cm = float(input("enter height in cm: "))

# convert cm to meters first
height_m = height_cm / 100

# calculate bmi
bmi = weight / (height_m * height_m)

print(f"BMI: {bmi:.2f}")

if bmi < 18.5:
    print("Category: Underweight")
elif bmi <= 22.9:
    print("Category: Normal (Indian range — narrower than WHO)")
elif bmi <= 24.9:
    print("Category: Overweight")
elif bmi <= 29.9:
    print("Category: Obese Class I")
else:
    print("Category: Obese Class II")

enter weight in kg: 80
enter height in cm: 146
BMI: 37.53
Category: Obese Class II


C3


In [ ]:
n = int(input("enter n: "))

for i in range(1, n + 1):

    for j in range(1, i + 1):

        print(j, end=" ")


    print()

enter n: 5
1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [ ]:
n = int(input("enter n: "))
for i in range(1, n + 1):

    for s in range(n - i):
        print("  ", end="")

    for j in range(1, i + 1):
        print(j, end=" ")

    for j in range(i - 1, 0, -1):
        print(j, end=" ")

    print()

for i in range(n - 1, 0, -1):

    for s in range(n - i):
        print("  ", end="")

    for j in range(1, i + 1):
        print(j, end=" ")

    for j in range(i - 1, 0, -1):
        print(j, end=" ")

    print()

enter n: 5
        1 
      1 2 1 
    1 2 3 2 1 
  1 2 3 4 3 2 1 
1 2 3 4 5 4 3 2 1 
  1 2 3 4 3 2 1 
    1 2 3 2 1 
      1 2 1 
        1 


In [ ]:
rows = 5

for i in range(rows):

    for s in range(rows - i - 1):
        print(" ", end="")

    val = 1

    for j in range(i + 1):
        print(val, end=" ")

        val = val * (i - j) // (j + 1)

    print()

    1 
   1 1 
  1 2 1 
 1 3 3 1 
1 4 6 4 1 


In [ ]:
n = int(input("enter n: "))

for i in range(1, n + 1):
    for j in range(i):
        print(chr(65 + j), end=" ")
    print()

enter n: 5
A 
A B 
A B C 
A B C D 
A B C D E 


C4

In [ ]:
# question 31
count = 0
first = True

for num in range(1, 10000):
    temp = num
    n = 0
    while temp > 0:
        n = n + 1
        temp = temp // 10

    temp = num
    total = 0
    while temp > 0:
        digit = temp % 10
        total = total + (digit ** n)
        temp = temp // 10

    if total == num:
        if first:
            print(num, end="")
            first = False
        else:
            print(",", num, end="")
        count = count + 1

print()
print("Total count:", count)

1, 2, 3, 4, 5, 6, 7, 8, 9, 153, 370, 371, 407, 1634, 8208, 9474
Total count: 16


In [ ]:
# question 32
n = int(input("enter n: "))

a = 0
b = 1
total = 0

if n >= 1:
    print(a, end=" ")
    total = total + a

if n >= 2:
    print(b, end=" ")
    total = total + b

for i in range(2, n):
    c = a + b
    print(c, end=" ")
    total = total + c
    a = b
    b = c

if n > 0:
    print()

print("Sum:", total)

enter n: 1
0 
Sum: 0


In [ ]:
# question 33
is_prime = True
if n <= 1:
    is_prime = False
else:
    i = 2
    while i * i <= n:
        if n % i == 0:
            is_prime = False
            break
        i = i + 1

if is_prime:
    print(n, "is prime")
else:
    print(n, "is not prime")

prime_sum = 0
for num in range(2, n + 1):
    check_prime = True
    j = 2
    while j * j <= num:
        if num % j == 0:
            check_prime = False
            break
        j = j + 1

    if check_prime:
        prime_sum = prime_sum + num

print("Sum of primes:", prime_sum)

1 is not prime
Sum of primes: 0


In [ ]:
n = int(input("enter a number: "))

temp = n
if temp < 0:
    temp = temp * -1

rev = 0
while temp > 0:
    digit = temp % 10
    rev = (rev * 10) + digit
    temp = temp // 10

if n < 0:
    rev = rev * -1

print("Reversed:", rev)

if n < 0:
    print(n, "is not a palindrome")
elif n == rev:
    print(n, "is a palindrome")
else:
    print(n, "is not a palindrome")


enter a number: -122
Reversed: -221
-122 is not a palindrome


In [ ]:
# question 34
a = int(input("enter first positive integer: "))
b = int(input("enter second positive integer: "))

temp_a = a
temp_b = b

while temp_b > 0:
    rem = temp_a % temp_b
    temp_a = temp_b
    temp_b = rem

hcf = temp_a
lcm = (a * b) // hcf

print("HCF:", hcf)
print("LCM:", lcm)

enter first positive integer: 5
enter second positive integer: 3
HCF: 1
LCM: 15


In [ ]:
# question 35
text = input("enter a sentence: ")

total_chars = 0
words = 0
vowels = 0
consonants = 0
digits = 0
spaces = 0
specials = 0

in_word = False

for char in text:
    total_chars = total_chars + 1

    if char == " ":
        spaces = spaces + 1
        in_word = False
    else:
        if not in_word:
            words = words + 1
            in_word = True

        c = char.lower()
        if c == 'a' or c == 'e' or c == 'i' or c == 'o' or c == 'u':
            vowels = vowels + 1
        elif c.isalpha():
            consonants = consonants + 1
        elif char.isdigit():
            digits = digits + 1
        else:
            specials = specials + 1

print("Total characters:", total_chars)
print("Total words:", words)
print("Vowels:", vowels)
print("Consonants:", consonants)
print("Digits:", digits)
print("Spaces:", spaces)
print("Special characters:", specials)

enter a sentence: happy birthday to me
Total characters: 20
Total words: 4
Vowels: 5
Consonants: 12
Digits: 0
Spaces: 3
Special characters: 0


C5


In [ ]:
# question 37
data = input("enter 10 marks separated by space: ")
str_marks = data.split()

marks = []
for s in str_marks:
    marks.append(int(s))

max1 = -1
max2 = -1
min_val = 101
total = 0

for m in marks:
    total = total + m

    if m < min_val:
        min_val = m

    if m > max1:
        max2 = max1
        max1 = m
    elif m > max2 and m != max1:
        max2 = m

avg = total / 10

above_avg_count = 0
for m in marks:
    if m > avg:
        above_avg_count = above_avg_count + 1

print("Maximum:", max1)
print("Minimum:", min_val)
print("Average:", avg)
print("Students above average:", above_avg_count)
print("Second highest:", max2)

enter 10 marks separated by space: 60 50 80 90 70 40 85 65 75 95
Maximum: 95
Minimum: 40
Average: 71.0
Students above average: 5
Second highest: 90


In [ ]:
text = input("enter a review: ").lower() + " "
freq = {}
word = ""

for char in text:
    if char.isalpha() or char.isdigit():
        word = word + char
    else:
        if word != "":
            if word in freq:
                freq[word] = freq[word] + 1
            else:
                freq[word] = 1
            word = ""

words_list = []
counts_list = []

for k in freq:
    words_list.append(k)
    counts_list.append(freq[k])

size = 0
for w in words_list:
    size = size + 1

for i in range(size):
    for j in range(0, size - i - 1):
        if counts_list[j] < counts_list[j + 1]:
            temp_c = counts_list[j]
            counts_list[j] = counts_list[j + 1]
            counts_list[j + 1] = temp_c

            temp_w = words_list[j]
            words_list[j] = words_list[j + 1]
            words_list[j + 1] = temp_w

for i in range(size):
    print(words_list[i] + ":", counts_list[i])

if size > 0:
    print("Most frequent word:", words_list[0], "-", counts_list[0])

enter a review: Excellent service! The food arrived piping hot, well before the estimated delivery time, and the packaging was perfectly spill-proof.
the: 3
excellent: 1
service: 1
food: 1
arrived: 1
piping: 1
hot: 1
well: 1
before: 1
estimated: 1
delivery: 1
time: 1
and: 1
packaging: 1
was: 1
perfectly: 1
spill: 1
proof: 1
Most frequent word: the - 3


In [ ]:
states = {
    "karnataka": "bengaluru",
    "maharashtra": "mumbai",
    "telangana": "hyderabad",
    "tamil nadu": "chennai",
    "kerala": "thiruvananthapuram"
}

while True:
    print("\n--- Menu ---")
    print("1. Add a new state-capital pair")
    print("2. Update an existing capital")
    print("3. Delete a state")
    print("4. Search a state")
    print("5. Display all states sorted alphabetically")
    print("6. Exit")

    choice = input("Enter your choice (1-6): ")

    if choice == '1':
        state = input("Enter state name: ").lower()
        capital = input("Enter capital name: ").lower()
        states[state] = capital
        print("Added successfully.")

    elif choice == '2':
        state = input("Enter state name to update: ").lower()
        if state in states:
            capital = input("Enter new capital name: ").lower()
            states[state] = capital
            print("Updated successfully.")
        else:
            print("State not found.")

    elif choice == '3':
        state = input("Enter state name to delete: ").lower()
        if state in states:
            del states[state]
            print("Deleted successfully.")
        else:
            print("State not found.")

    elif choice == '4':
        state = input("Enter state name to search: ").lower()
        if state in states:
            print("Capital:", states[state])
        else:
            print("Not found.")

    elif choice == '5':
        keys_list = []
        for k in states:
            keys_list.append(k)

        size = 0
        for k in keys_list:
            size = size + 1

        for i in range(size):
            for j in range(0, size - i - 1):
                if keys_list[j] > keys_list[j + 1]:
                    temp = keys_list[j]
                    keys_list[j] = keys_list[j + 1]
                    keys_list[j + 1] = temp

        for k in keys_list:
            print(k, "->", states[k])

    elif choice == '6':
        print("Exiting...")
        break

    else:
        print("Invalid choice, please try again.")


--- Menu ---
1. Add a new state-capital pair
2. Update an existing capital
3. Delete a state
4. Search a state
5. Display all states sorted alphabetically
6. Exit
karnataka -> bengaluru
kerala -> thiruvananthapuram
maharashtra -> mumbai
tamil nadu -> chennai
telangana -> hyderabad

--- Menu ---
1. Add a new state-capital pair
2. Update an existing capital
3. Delete a state
4. Search a state
5. Display all states sorted alphabetically
6. Exit
karnataka -> bengaluru
kerala -> thiruvananthapuram
maharashtra -> mumbai
tamil nadu -> chennai
telangana -> hyderabad

--- Menu ---
1. Add a new state-capital pair
2. Update an existing capital
3. Delete a state
4. Search a state
5. Display all states sorted alphabetically
6. Exit
Not found.

--- Menu ---
1. Add a new state-capital pair
2. Update an existing capital
3. Delete a state
4. Search a state
5. Display all states sorted alphabetically
6. Exit


In [ ]:
section_a = {"Python", "Java", "C++", "SQL"}
section_b = {"Java", "JavaScript", "Python", "Go", "SQL"}

both = section_a & section_b
print("Languages known by BOTH sections:", both)

only_a = section_a - section_b
print("Languages known ONLY by Section A:", only_a)

only_b = section_b - section_a
print("Languages known ONLY by Section B:", only_b)

total_unique = section_a | section_b
print("Total unique languages across both sections:", total_unique)

exclusive = section_a ^ section_b
print("Languages exclusive to one section but not both:", exclusive)

In [ ]:
 prices = (3845, 3902, 3878, 3955, 4012, 3998, 4055)
days = ("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")

max_price = 0
min_price = 10000000
max_day = ""
min_day = ""
total = 0

max_gain = 0
gain_day1 = ""
gain_day2 = ""
volatility = 0

for i in range(7):
    price = prices[i]

    if price > max_price:
        max_price = price
        max_day = days[i]

    if price < min_price:
        min_price = price
        min_day = days[i]

    total = total + price

    if i > 0:
        prev_price = prices[i - 1]
        diff = price - prev_price

        if diff > max_gain:
            max_gain = diff
            gain_day1 = days[i - 1]
            gain_day2 = days[i]

        abs_diff = diff
        if abs_diff < 0:
            abs_diff = -abs_diff

        volatility = volatility + abs_diff

avg = total / 7

print("Maximum price:", max_price, "on", max_day)
print("Minimum price:", min_price, "on", min_day)
print("Average price:", avg)
print("Biggest single-day gain:", max_gain, "between", gain_day1, "and", gain_day2)
print("Total volatility:", volatility)

In [ ]:
nums = [12, 5, 8, 12, 19, 5, 3, 20, 8, 1, 15, 12, 7, 3, 9, 20, 11, 4, 1, 5]

freq = {}
for n in nums:
    if n in freq:
        freq[n] = freq[n] + 1
    else:
        freq[n] = 1

unique_set = set()
for n in nums:
    unique_set.add(n)

more_than_once = []
exactly_once = []

for k in freq:
    if freq[k] > 1:
        more_than_once.append(k)
    elif freq[k] == 1:
        exactly_once.append(k)

print("Set of unique numbers:", unique_set)
print("Numbers appearing more than once:", more_than_once)
print("Numbers appearing exactly once:", exactly_once)

C6


In [ ]:
text = input("enter a sentence: ")

cleaned = ""
for char in text:
    if char.isalpha() or char.isdigit():
        cleaned = cleaned + char.lower()

reversed_cleaned = ""
for char in cleaned:
    reversed_cleaned = char + reversed_cleaned

if cleaned == reversed_cleaned:
    print("TRUE")
else:
    print("FALSE")

In [ ]:
ext = input("enter a sentence: ")

length = 0
for char in text:
    length = length + 1

result = ""
new_word = True

for i in range(length):
    if text[i] == " ":
        result = result + text[i]
        new_word = True
    else:
        if new_word:
            result = result + text[i].upper()
            new_word = False
        else:
            result = result + text[i].lower()

print(result)

In [ ]:
text = input("enter a message: ")
n = int(input("enter shift value: "))

result = ""

for char in text:
    if char >= 'A' and char <= 'Z':
        shift = (ord(char) - 65 + n) % 26
        result = result + chr(65 + shift)
    elif char >= 'a' and char <= 'z':
        shift = (ord(char) - 97 + n) % 26
        result = result + chr(97 + shift)
    else:
        result = result + char

print(result)

C7

In [ ]:
def calculate_gst(amount, gst_rate=18, gst_inclusive=False):
    if gst_inclusive:
        total_amount = float(amount)
        base_amount = total_amount / (1 + (gst_rate / 100))
        gst_amount = total_amount - base_amount
    else:
        base_amount = float(amount)
        gst_amount = base_amount * (gst_rate / 100)
        total_amount = base_amount + gst_amount

    return (round(base_amount, 2), round(gst_amount, 2), round(total_amount, 2))

print(calculate_gst(1000))
print(calculate_gst(1180, gst_inclusive=True))
print(calculate_gst(500, gst_rate=5))

In [ ]:
# question 47
def power(base, exp):
    if exp == 0:
        return 1
    elif exp < 0:
        return 1 / power(base, -exp)
    else:
        return base * power(base, exp - 1)

print(power(2, 10))
print(power(5, 0))
print(power(3, -2))

In [3]:
# question 48
import numpy as np

matrix = np.eye(5)
print("Original 5x5 Identity Matrix:")
print(matrix)

matrix_10 = matrix * 10
print("\nMultiplied by 10:")
print(matrix_10)

matrix_t = np.transpose(matrix_10)
print("\nTransposed Matrix:")
print(matrix_t)

diag_sum = np.trace(matrix_t)
print("\nSum of diagonal elements:", diag_sum)

total_sum = np.sum(matrix_t)
print("Sum of all elements:", total_sum)

Original 5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Multiplied by 10:
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]

Transposed Matrix:
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]

Sum of diagonal elements: 50.0
Sum of all elements: 50.0


In [5]:
# question 49
import numpy as np

sales = np.array([12000, 18500, 14200, 22100, 19800, 35200, 28400])
days = np.array(["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"])

total_sales = np.sum(sales)
avg_sales = np.mean(sales)
max_day = days[np.argmax(sales)]
above_avg = np.sum(sales > avg_sales)
growth = ((sales[-1] - sales[0]) / sales[0]) * 100
dod_changes = (np.diff(sales) / sales[:-1]) * 100

print("Total weekly sales:", total_sales)
print("Daily average:", round(avg_sales, 2))
print("Maximum sales day:", max_day)
print("Days above weekly average:", above_avg)
print("Percentage growth Mon to Sun:", round(growth, 2))
print("Day-on-day % changes:", np.round(dod_changes, 2))

Total weekly sales: 150200
Daily average: 21457.14
Maximum sales day: Saturday
Days above weekly average: 3
Percentage growth Mon to Sun: 136.67
Day-on-day % changes: [ 54.17 -23.24  55.63 -10.41  77.78 -19.32]


In [6]:
# question 50
import numpy as np

matrix = np.ones((5, 5), dtype=int)
matrix[1:-1, 1:-1] = 0

print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
